version: '2'

services:
  wordpress:
    build: .
    environment:
      WORDPRESS_DB_PASSWORD: example
    links:
      - db:mysql
    ports:
      - "80:80"
    volumes:
      - ./app/wp-content:/var/www/html/wp-content

  db:
    image: mariadb:10.1.17
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: {}
