version: '2'

services:
  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_wordpress
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_USER: app
    links:
      - db:mysql
    ports:
      - "80:80"
    volumes:
      - ./app/wp-content:/var/www/html/wp-content

  db:
    image: mysql:5.7.26
    environment:
      MYSQL_DATABASE: wp_wordpress
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: app
    ports:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: {}
